modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="brvsb" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Rubidium Video Settings Button" #mandatory
logoFile="icon.png" #optional
authors="LimeShulkerBox,TexTrue" #optional
description='''
Removes Rubidium annoyances with their stupid video settings menu'''

[[dependencies.brvsb]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.brvsb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.brvsb]]
    modId="rubidium"
    mandatory=true
    versionRange="[0.2, )"

[[dependencies.brvsb]]
    modId="magnesium"
    mandatory=true
    versionRange="[0.2, )"

[[dependencies.brvsb]]
    modId="halogen"
    mandatory=true
    versionRange="[0.2, )"

[[dependencies.brvsb]]
    modId="halogen"
    mandatory=true
    versionRange="[0.2, )"

[[dependencies.brvsb]]
    modId="chlorine"
    mandatory=true
    versionRange="[0.0.1, )"